# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('address', models.CharField(max_length=200, verbose_name='家庭地址')),
                ('message', models.CharField(max_length=200, verbose_name='留言信息')),
            ],
            options={
                'verbose_name': '用户留言信息',
                'db_table': 'UserMessage',
                'ordering': ('-object_id',),
            },
        ),
    ]
